
CREATE SEQUENCE SQ_ID_BRAND START WITH 1 INCREMENT BY 1;

CREATE TABLE T_BRAND (
    ID NUMBER(38) NOT NULL,
    CODE VARCHAR2(255) NOT NULL,
	TITLE VARCHAR2(55) NOT NULL,
    CONSTRAINT PK_ID_BRAND PRIMARY KEY (ID)
);

---------------------------------------------------------

CREATE SEQUENCE SQ_ID_MODEL START WITH 1 INCREMENT BY 1;

CREATE TABLE T_MODEL (
    ID NUMBER(38) NOT NULL,
    CODE VARCHAR2(255) NOT NULL,
	TITLE VARCHAR2(255) NOT NULL,
    FK_BRAND NUMBER(38) NOT NULL,
    CONSTRAINT FK_ID_BRAND_IN_MODEL FOREIGN KEY (FK_BRAND) REFERENCES T_BRAND(ID),
    CONSTRAINT PK_ID_MODEL PRIMARY KEY (ID)
);

---------------------------------------------------------

CREATE SEQUENCE SQ_ID_OWNER START WITH 1 INCREMENT BY 1;

CREATE TABLE T_OWNER (
    ID NUMBER(38) NOT NULL,
    FIRST_NAME VARCHAR2(255) NOT NULL,
    LAST_NAME VARCHAR2(255) NOT NULL,
    BIRTHDATE DATE NOT NULL,
    MAIL VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_ID_OWNER PRIMARY KEY (ID)
);

---------------------------------------------------------

CREATE SEQUENCE SQ_ID_CAR_OWNER START WITH 1 INCREMENT BY 1;

CREATE TABLE T_CAR_OWNER (
    ID NUMBER(38) NOT NULL,
    FK_OWNER NUMBER(38) NOT NULL,
    FK_MODEL NUMBER(38) NOT NULL,
    PURCHASE_DATE DATE NOT NULL,
    SELL_DATE DATE,
    CONSTRAINT FK_ID_OWNER_IN_CAR FOREIGN KEY (FK_OWNER) REFERENCES T_OWNER(ID),
    CONSTRAINT FK_ID_MODEL_IN_CAR FOREIGN KEY (FK_MODEL) REFERENCES T_MODEL(ID),
    CONSTRAINT PK_ID_CAR PRIMARY KEY (ID)
);



